import type {
  AssetOverlaySuitability,
  AssetRole,
  AssetSwColorMode
} from "@/lib/types";

export type PrioritizedAsset = {
  id: string;
  /** Öffentlicher Auslieferungspfad für Frontend-Verwendung; muss mit /assets/dama-venus/ beginnen. */
  finalPath: string;
  /** Pipeline-Inputpfad aus nicht-public Quellen (pics/ oder assets-src/dama-venus/), niemals public/. */
  sourcePath: string;
  area: "home" | "music" | "visuals" | "about" | "press";
  recommendedModuleType: string;
  altDraft: string;
  cropHint: string;
  focusHint: string;
  swColorMode: AssetSwColorMode;
  overlaySuitability: AssetOverlaySuitability;
  priority: number;
  role: AssetRole;
  copyKey?: string;
  /** Wenn true: fehlende Quelle wird als Warnung behandelt, nicht als Fehler. Für Assets, die noch nicht geliefert wurden. */
  optional?: boolean;
};

export const prioritizedAssets: PrioritizedAsset[] = [
  {
    id: "home-lead-portrait",
    finalPath: "/assets/dama-venus/visuals/editorial/img-4821-portrait-v01.jpg",
    sourcePath: "pics/IMG_4821.jpg",
    area: "home",
    recommendedModuleType: "image",
    altDraft: "Dáma Venus at Fontana di Trevi, Roma — cinematic editorial portrait",
    cropHint: "Full-width cinematic poster crop",
    focusHint: "Keep figure centered with Trevi Fountain architecture visible",
    swColorMode: "good",
    overlaySuitability: "supports-dark-overlay",
    priority: 100,
    role: "decorative"
  },
  {
    id: "home-release-cover",
    finalPath: "/assets/dama-venus/home/dv_home_release_cover_primary_color_4x5_v01.jpg",
    sourcePath: "pics/spotify_canvas_9x16.jpg",
    area: "home",
    recommendedModuleType: "image",
    altDraft: "Current Chapter cover",
    cropHint: "Center crop",
    focusHint: "Keep title and artist fully visible",
    swColorMode: "good",
    overlaySuitability: "no-overlay",
    priority: 1,
    role: "informative"
  },
  {
    id: "home-visual-preview",
    finalPath: "/assets/dama-venus/visuals/dv_visuals_frames_portrait_color_4x3_v01.jpg",
    sourcePath: "pics/3.jpeg",
    area: "home",
    recommendedModuleType: "image",
    altDraft: "Dáma Venus — Frames in Motion editorial portrait",
    cropHint: "Landscape crop, subject left-center",
    focusHint: "Subject centered, face at upper-center",
    swColorMode: "excellent",
    overlaySuitability: "supports-dark-overlay",
    priority: 2,
    role: "decorative"
  },
  {
    id: "home-statement-editorial",
    finalPath: "/assets/dama-venus/visuals/editorial/gduuz-portrait-v01.jpg",
    sourcePath: "pics/GDUUZ.JPG",
    area: "home",
    recommendedModuleType: "background",
    altDraft: "Dáma Venus — editorial portrait, statement background",
    cropHint: "Portrait crop, centered on figure",
    focusHint: "Center on face/upper body for text overlay",
    swColorMode: "excellent",
    overlaySuitability: "supports-dark-overlay",
    priority: 3,
    role: "decorative"
  },
  {
    id: "home-contact-newsletter",
    finalPath: "/assets/dama-venus/home/dv_home_release_cover_primary_color_4x5_v01.jpg",
    sourcePath: "pics/spotify_canvas_9x16.jpg",
    area: "home",
    recommendedModuleType: "image",
    altDraft: "Contact and newsletter module visual",
    cropHint: "Center crop",
    focusHint: "Keep central motif visible",
    swColorMode: "good",
    overlaySuitability: "supports-dark-overlay",
    priority: 4,
    role: "decorative"
  },
  {
    id: "home-press-preview",
    finalPath: "/assets/dama-venus/home/dv_home_lead_portrait_main_color_3x4_v01.jpeg",
    sourcePath: "pics/Cinderela-241.jpg",
    area: "home",
    recommendedModuleType: "image",
    altDraft: "Home press preview portrait",
    cropHint: "Portrait crop",
    focusHint: "Keep face centered with headroom",
    swColorMode: "excellent",
    overlaySuitability: "supports-dark-overlay",
    priority: 5,
    role: "informative"
  },

  {
    id: "music-current-chapter-cover",
    finalPath: "/assets/dama-venus/visuals/editorial/cover-neon-portrait-v01.png",
    sourcePath: "pics/cover.png",
    area: "music",
    recommendedModuleType: "featured-release",
    altDraft: "Current Chapter — neon magenta portrait by Dáma Venus",
    cropHint: "4:5 center crop with title-safe area",
    focusHint: "Keep artist and release title visible in center",
    swColorMode: "good",
    overlaySuitability: "no-overlay",
    priority: 1,
    role: "informative"
  },
  {
    id: "music-current-chapter-visual",
    finalPath: "/assets/dama-venus/music/dv_music_current_chapter_visual_color_16x9_v01.jpg",
    sourcePath: "pics/spotify_canvas_9x16.jpg",
    area: "music",
    recommendedModuleType: "visual-release",
    altDraft: "Current Chapter visual frame",
    cropHint: "16:9 cinematic crop",
    focusHint: "Preserve central subject and negative space for text",
    swColorMode: "good",
    overlaySuitability: "supports-dark-overlay",
    priority: 2,
    role: "informative"
  },
  {
    id: "music-midnight-signal-cover",
    finalPath: "/assets/dama-venus/music/dv_music_midnight_signal_cover_bw_4x5_v01.jpg",
    sourcePath: "pics/Cinderela-210.JPEG",
    area: "music",
    recommendedModuleType: "release-card",
    altDraft: "Midnight Signal single artwork",
    cropHint: "4:5 portrait crop",
    focusHint: "Keep face and shoulder line in upper center",
    swColorMode: "excellent",
    overlaySuitability: "supports-dark-overlay",
    priority: 3,
    role: "informative"
  },
  {
    id: "music-afterglow-cut-cover",
    finalPath: "/assets/dama-venus/music/dv_music_afterglow_cut_cover_color_3x2_v01.jpg",
    sourcePath: "pics/Pink and Purple.png",
    area: "music",
    recommendedModuleType: "release-card",
    altDraft: "Afterglow Cut release artwork",
    cropHint: "Center crop, subject centered",
    focusHint: "Center on subject",
    swColorMode: "excellent",
    overlaySuitability: "supports-dark-overlay",
    priority: 4,
    role: "informative"
  },
  {
    id: "music-nocturne-line-visual",
    finalPath: "/assets/dama-venus/music/dv_music_nocturne_line_visual_color_3x2_v01.jpg",
    sourcePath: "pics/ChatGPT Image Apr 13, 2026, 04_13_26 PM.png",
    area: "music",
    recommendedModuleType: "video-link",
    altDraft: "Nocturne Line visual sequence",
    cropHint: "3:2 landscape crop",
    focusHint: "Center on subject",
    swColorMode: "excellent",
    overlaySuitability: "supports-dark-overlay",
    priority: 5,
    role: "informative"
  },
  {
    id: "visuals-cinderela-lead-241",
    finalPath: "/assets/dama-venus/visuals/dv_visuals_cinderela_lead_241_color_3x4_v01.jpg",
    sourcePath: "pics/Cinderela-241.jpg",
    area: "visuals",
    recommendedModuleType: "series-section",
    altDraft: "Cinderela series lead portrait frame",
    cropHint: "Portrait 4:5 or 3:4 crop",
    focusHint: "Keep eyes and upper torso centered with top breathing room",
    swColorMode: "excellent",
    overlaySuitability: "supports-dark-overlay",
    priority: 1,
    role: "informative"
  },
  {
    id: "visuals-night-portrait-0e9128",
    finalPath: "/assets/dama-venus/visuals/editorial/0e912806-night-portrait-v01.jpg",
    sourcePath: "pics/0E912806-184C-4164-9441-5501C3010BB3.JPG",
    area: "visuals",
    recommendedModuleType: "lead-sequence",
    altDraft: "Dáma Venus — night portrait in car with dog, pink outfit",
    cropHint: "Portrait 3:4 crop",
    focusHint: "Keep face and upper body centered, dog visible",
    swColorMode: "excellent",
    overlaySuitability: "supports-dark-overlay",
    priority: 1,
    role: "informative"
  },
  {
    id: "contact-red-portrait-69bf",
    finalPath: "/assets/dama-venus/visuals/editorial/69bf1c97-c7f0-4855-b2f0-5d50840a153f-landscape-v01.jpg",
    sourcePath: "pics/69BF1C97-C7F0-4855-B2F0-5D50840A153F.JPG",
    area: "home",
    recommendedModuleType: "background",
    altDraft: "Dáma Venus — editorial portrait with red backdrop, black outfit",
    cropHint: "Landscape 16:9 crop",
    focusHint: "Keep face and upper body centered",
    swColorMode: "excellent",
    overlaySuitability: "supports-dark-overlay",
    priority: 1,
    role: "decorative"
  },
  {
    id: "visuals-cinderela-frame-243",
    finalPath: "/assets/dama-venus/visuals/dv_visuals_ret_portrait_v01.png",
    sourcePath: "pics/RET.png",
    area: "visuals",
    recommendedModuleType: "series-section",
    altDraft: "Cinderela series portrait with editorial lighting",
    cropHint: "Portrait crop with headroom",
    focusHint: "Maintain face center and shoulder line",
    swColorMode: "excellent",
    overlaySuitability: "supports-dark-overlay",
    priority: 2,
    role: "informative"
  },
  {
    id: "visuals-cinderela-frame-288",
    finalPath: "/assets/dama-venus/visuals/dv_visuals_cinderela_frame_288_bw_3x4_v01.jpeg",
    sourcePath: "pics/Cinderela-288.JPEG",
    area: "visuals",
    recommendedModuleType: "series-section",
    altDraft: "Cinderela series portrait close frame",
    cropHint: "Portrait crop; avoid tight chin crop",
    focusHint: "Keep eyes above midpoint for editorial balance",
    swColorMode: "good",
    overlaySuitability: "supports-dark-overlay",
    priority: 3,
    role: "informative"
  },
  {
    id: "visuals-cinderela-landscape-210",
    finalPath: "/assets/dama-venus/visuals/dv_visuals_cinderela_landscape_210_bw_16x9_v01.jpeg",
    sourcePath: "pics/Cinderela-210.JPEG",
    area: "visuals",
    recommendedModuleType: "editorial-image-row",
    altDraft: "Cinderela landscape frame with cinematic staging",
    cropHint: "16:9 or 3:2 landscape crop",
    focusHint: "Keep subject centered to protect mobile crop stability",
    swColorMode: "good",
    overlaySuitability: "supports-dark-overlay",
    priority: 4,
    role: "informative"
  },
  {
    id: "visuals-uuid-6824",
    finalPath: "/assets/dama-venus/visuals/dv_visuals_uuid_6824_color_16x9_v01.jpg",
    sourcePath: "pics/6824A7C6-3A24-4408-8BDF-F7A237F5FD41.JPG",
    area: "visuals",
    recommendedModuleType: "editorial-image-row",
    altDraft: "Wide visual frame with color accent lighting",
    cropHint: "Wide landscape crop",
    focusHint: "Protect center-right action line",
    swColorMode: "limited",
    overlaySuitability: "no-overlay",
    priority: 5,
    role: "informative"
  },
  {
    id: "visuals-uuid-3493",
    finalPath: "/assets/dama-venus/visuals/dv_visuals_uuid_3493_color_3x4_v01.jpg",
    sourcePath: "pics/349343D2-8AD2-4A03-8893-E2C94FC1D7BF.JPG",
    area: "visuals",
    recommendedModuleType: "editorial-image-row",
    altDraft: "Portrait frame used as transition in visuals flow",
    cropHint: "Portrait 3:4 crop",
    focusHint: "Keep face and gaze axis centered",
    swColorMode: "good",
    overlaySuitability: "supports-dark-overlay",
    priority: 6,
    role: "informative"
  },
  {
    id: "visuals-portrait-tamiris-12",
    finalPath: "/assets/dama-venus/visuals/dv_visuals_portrait_img4671_v01.jpg",
    sourcePath: "pics/IMG_4671.JPEG",
    area: "visuals",
    recommendedModuleType: "large-image-block",
    altDraft: "Dáma Venus — close-up portrait",
    cropHint: "Center crop, face centered",
    focusHint: "Keep face and hands in frame center",
    swColorMode: "excellent",
    overlaySuitability: "supports-dark-overlay",
    priority: 7,
    role: "informative"
  },
  {
    id: "visuals-still-unnamed-1",
    finalPath: "/assets/dama-venus/visuals/dv_visuals_still_unnamed_01_bw_1x1_v01.webp",
    sourcePath: "pics/unnamed.webp",
    area: "visuals",
    recommendedModuleType: "grid",
    altDraft: "Square still for texture break",
    cropHint: "1:1 unchanged",
    focusHint: "Center detail for small tile rendering",
    swColorMode: "excellent",
    overlaySuitability: "no-overlay",
    priority: 8,
    role: "decorative"
  },
  {
    id: "visuals-still-unnamed-2",
    finalPath: "/assets/dama-venus/visuals/dv_visuals_still_unnamed_02_bw_1x1_v01.webp",
    sourcePath: "pics/unnamed (2).webp",
    area: "visuals",
    recommendedModuleType: "grid",
    altDraft: "Square still with low-intensity mood",
    cropHint: "1:1 unchanged",
    focusHint: "Keep center texture for grid consistency",
    swColorMode: "excellent",
    overlaySuitability: "no-overlay",
    priority: 9,
    role: "decorative"
  },
  {
    id: "visuals-still-unnamed-3",
    finalPath: "/assets/dama-venus/visuals/dv_visuals_still_unnamed_03_bw_1x1_v01.webp",
    sourcePath: "pics/unnamed (3).webp",
    area: "visuals",
    recommendedModuleType: "grid",
    altDraft: "Square still used as calm spacer image",
    cropHint: "1:1 unchanged",
    focusHint: "Center-safe composition",
    swColorMode: "excellent",
    overlaySuitability: "no-overlay",
    priority: 10,
    role: "decorative"
  },
  {
    id: "visuals-linked-current-chapter",
    finalPath: "/assets/dama-venus/visuals/dv_visuals_linked_current_chapter_color_9x16_v01.jpg",
    sourcePath: "pics/spotify_canvas_9x16.jpg",
    area: "visuals",
    recommendedModuleType: "linked-visual-module",
    altDraft: "Current Chapter linked visual frame",
    cropHint: "Tall 9:16 crop",
    focusHint: "Keep subject centered for tall mobile module",
    swColorMode: "limited",
    overlaySuitability: "supports-dark-overlay",
    priority: 11,
    role: "informative"
  },
  {
    id: "about-intro-entry-portrait-primary",
    finalPath: "/assets/dama-venus/visuals/editorial/2041e42a-402e-44db-8a68-0c89122ee9b9-portrait-v01.jpg",
    sourcePath: "pics/2041E42A-402E-44DB-8A68-0C89122EE9B9.JPG",
    area: "about",
    recommendedModuleType: "about-intro-lead",
    altDraft: "Dáma Venus — neon magenta studio portrait",
    cropHint: "Portrait crop with safe headroom",
    focusHint: "Keep face and upper body centered, magenta background visible",
    swColorMode: "excellent",
    overlaySuitability: "supports-dark-overlay",
    priority: 100,
    role: "informative"
  },
  {
    id: "about-intro-entry-portrait-secondary",
    finalPath: "/assets/dama-venus/about/dv_about_intro_entry_portrait_secondary_bw_3x4_v01.jpeg",
    sourcePath: "pics/Cinderela-243.JPEG",
    area: "about",
    recommendedModuleType: "about-intro-lead",
    altDraft: "Dama Venus supporting entry portrait for intro block",
    cropHint: "Portrait crop with upper-body framing",
    focusHint: "Maintain centered face and shoulder line",
    swColorMode: "excellent",
    overlaySuitability: "supports-dark-overlay",
    priority: 90,
    role: "informative"
  },
  {
    id: "about-supporting-visual-calm-01",
    finalPath: "/assets/dama-venus/about/dv_about_supporting_visual_calm_01_bw_16x9_v01.jpeg",
    sourcePath: "pics/Cinderela-210.JPEG",
    area: "about",
    recommendedModuleType: "about-supporting-visual",
    altDraft: "",
    cropHint: "16:9 landscape crop for calm image module",
    focusHint: "Protect subject center with space around silhouette",
    swColorMode: "good",
    overlaySuitability: "supports-dark-overlay",
    priority: 40,
    role: "decorative"
  },
  {
    id: "about-supporting-visual-calm-02",
    finalPath: "/assets/dama-venus/about/dv_about_supporting_visual_calm_02_color_3x4_v01.jpeg",
    sourcePath: "pics/Tamiris-12.JPEG",
    area: "about",
    recommendedModuleType: "about-supporting-visual",
    altDraft: "",
    cropHint: "Portrait 4:5 crop with face-safe area",
    focusHint: "Keep face in upper center and retain soft shoulder contour",
    swColorMode: "excellent",
    overlaySuitability: "supports-dark-overlay",
    priority: 30,
    role: "decorative"
  },
  {
    id: "about-supporting-visual-calm-reserve-03",
    finalPath: "/assets/dama-venus/about/dv_about_supporting_visual_calm_reserve_03_color_3x4_v01.jpg",
    sourcePath: "pics/349343D2-8AD2-4A03-8893-E2C94FC1D7BF.JPG",
    area: "about",
    recommendedModuleType: "about-supporting-visual",
    altDraft: "",
    cropHint: "Portrait 3:4 crop for flexible reserve placement",
    focusHint: "Keep gaze axis centered for stable responsive crops",
    swColorMode: "good",
    overlaySuitability: "supports-dark-overlay",
    priority: 10,
    role: "decorative"
  },
  {
    id: "press-featured-portrait-primary",
    finalPath: "/assets/dama-venus/press/dv_press_featured_portrait_primary_color_3x4_v01.jpg",
    sourcePath: "pics/Cinderela-241.jpg",
    area: "press",
    recommendedModuleType: "featured-press-image",
    altDraft: "Featured press portrait of Dama Venus, primary selection",
    cropHint: "Portrait 3:4 crop with headroom",
    focusHint: "Keep face centered and maintain eye-line in upper third",
    swColorMode: "excellent",
    overlaySuitability: "supports-dark-overlay",
    priority: 1,
    role: "informative"
  },
  {
    id: "press-featured-portrait-secondary",
    finalPath: "/assets/dama-venus/press/dv_press_featured_portrait_secondary_bw_3x4_v01.jpg",
    sourcePath: "pics/Cinderela-243.JPEG",
    area: "press",
    recommendedModuleType: "featured-press-image",
    altDraft: "Secondary featured press portrait of Dama Venus",
    cropHint: "Portrait 3:4 crop with balanced shoulder framing",
    focusHint: "Keep face and shoulders centered for editorial crops",
    swColorMode: "excellent",
    overlaySuitability: "supports-dark-overlay",
    priority: 2,
    role: "informative"
  },
  {
    id: "press-editorial-landscape",
    finalPath: "/assets/dama-venus/press/dv_press_editorial_landscape_bw_16x9_v01.jpg",
    sourcePath: "pics/Cinderela-210.JPEG",
    area: "press",
    recommendedModuleType: "featured-press-image",
    altDraft: "Editorial landscape press image for wide placements",
    cropHint: "Landscape 16:9 crop with text-safe negative space",
    focusHint: "Keep subject centered for stable responsive trims",
    swColorMode: "good",
    overlaySuitability: "supports-dark-overlay",
    priority: 3,
    role: "informative"
  },
  {
    id: "press-detail-still",
    finalPath: "/assets/dama-venus/press/dv_press_detail_still_bw_1x1_v01.jpg",
    sourcePath: "pics/unnamed.webp",
    area: "press",
    recommendedModuleType: "featured-press-image",
    altDraft: "Detail still from Dama Venus press visual sequence",
    cropHint: "Square 1:1 crop preserving center detail",
    focusHint: "Maintain central texture and avoid clipping key detail",
    swColorMode: "good",
    overlaySuitability: "no-overlay",
    priority: 4,
    role: "decorative"
  },
  {
    id: "press-epk",
    finalPath: "/assets/dama-venus/press/dv_press_epk_document_v01.pdf",
    sourcePath: "assets-src/dama-venus/curated/dv_curated_press_epk_document_v01.pdf",
    area: "press",
    recommendedModuleType: "document",
    altDraft: "Dama Venus EPK",
    cropHint: "N/A for PDF",
    focusHint: "N/A for PDF",
    swColorMode: "n/a",
    overlaySuitability: "n/a",
    priority: 5,
    role: "informative",
    optional: true
  }
];
